const FETCH_POKEMONS = 'FETCH_POKEMONS';
const WILL_FETCH_POKEMONS = 'WILL_FETCH_POKEMONS';
const FETCHING_POKEMONS = 'FETCHING_POKEMONS';
const DID_FETCH_POKEMONS = 'DID_FETCH_POKEMONS';

export {
  FETCH_POKEMONS,
  WILL_FETCH_POKEMONS,
  FETCHING_POKEMONS,
  DID_FETCH_POKEMONS,
};
