const SIGN_IN = 'SIGN_IN';
const WILL_SIGN_IN = 'WILL_SIGN_IN';
const SIGNING_IN = 'SIGNING_IN';
const DID_SIGN_IN = 'DID_SIGN_IN';

const SIGN_OUT = 'SIGN_OUT';
const WILL_SIGN_OUT = 'WILL_SIGN_OUT';
const SIGNING_OUT = 'SIGNING_OUT';
const DID_SIGN_OUT = 'DID_SIGN_OUT';

export {
  SIGN_IN,
  WILL_SIGN_IN,
  SIGNING_IN,
  DID_SIGN_IN,

  SIGN_OUT,
  WILL_SIGN_OUT,
  SIGNING_OUT,
  DID_SIGN_OUT,
};
